services/web/backend/authentication/urls.py
from django.views.decorators.cache import cache_page
from django.views.decorators.vary import vary_on_headers
from django.contrib.auth import views as auth_views
from django.urls import path, reverse_lazy

from . import views

urlpatterns = [
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="authentication/login.html"),
        name="login",
    ),
    path("logout/", views.AuthenticationLogoutView.as_view(), name="logout"),
    path("oidc_logout/", views.OIDCLogoutView.as_view(), name="oidc_logout"),
    path(
        "password_reset/",
        auth_views.PasswordResetView.as_view(
            success_url=reverse_lazy("authentication:password_reset_done"),
            email_template_name="authentication/password_reset_email.html",
        ),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            success_url=reverse_lazy("authentication:password_reset_complete")
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
    path(
        "hasura/",
        cache_page(60)(
            vary_on_headers(
                "Authorization",
                "X-Hasura-User-Id",
                "X-Hasura-Role",
                "X-Hasura-AddOn-Id",
                "X-Hasura-AddOn-Permissions",
                "X-Hasura-Language",
                "User-Language",
            )(views.HasuraAuthWebhookView.as_view())
        ),
        name="hasura",
    ),
    path("media/", views.MediaAuthWebhookView.as_view()),
    path("", views.AuthenticationView.as_view(), name="index"),
    path("callback", views.AuthenticationCallbackView.as_view(), name="callback"),
    path(
        "terms_and_conditions/<consent_request_id>/",
        views.TermsAndConditionsConsentRequestView.as_view(),
        name="terms_and_conditions",
    ),
]

services/web/backend/docs/urls.py
import os
from pathlib import Path
import json

from django.urls import path
from django.conf import settings

from .views import DocsView, DocsSearchView

DOCS_BUILD_DIR = os.path.join(settings.BASE_DIR, "docs", "build")

urlpatterns = [path("search/", DocsSearchView.as_view(), name="search_results")]

if Path(DOCS_BUILD_DIR, "urlpatterns.json").exists():
    docs_urlpatterns = json.loads(Path(DOCS_BUILD_DIR, "urlpatterns.json").read_text())
    urlpatterns += [
        path(
            urlpattern["url"],
            DocsView.as_view(file_name=urlpattern["file_name"]),
            name=urlpattern["name"],
        )
        for urlpattern in docs_urlpatterns
    ]

services/web/backend/fastplatform/urls.py
from django.urls import include, path
from django.conf import settings
from django.views.generic import RedirectView, TemplateView
from django.conf.urls.i18n import i18n_patterns

from fastplatform.site import admin_site

urlpatterns = [
    path(
        "<string>/admin/login/",
        RedirectView.as_view(url=settings.LOGIN_URL, query_string=True),
        name="admin_login"
    ),
    path(
        "authentication/",
        include(("authentication.urls", "authentication"), namespace="authentication"),
    ),
    path("openid/", include("oidc_provider.urls")),
]

urlpatterns += i18n_patterns(
    path(
        "admin/all_objects/",
        admin_site.admin_view(admin_site.index_all_objects),
        name="all_objects",
    ),
    path("admin/", admin_site.urls),
    path("docs/", include(("docs.urls", "docs"), namespace="docs")),
    # Prefix needed for English as otherwise
    # the language selector for django-amin-interface
    # does not work
    prefix_default_language=True,
)

urlpatterns += [
    path("", RedirectView.as_view(url="/admin", query_string=True)),
    path("add_ons/", include(("add_ons.urls", "add_ons"), namespace="add_ons")),
    path("i18n/", include("django.conf.urls.i18n")),
]

if settings.ENABLE_GEOTAGGED_PHOTO:
    urlpatterns += [
        path("photos/", include("photos.urls")),
    ]

if settings.DEBUG and settings.DEBUG_TOOLBAR:
    # Debug toolbar
    import debug_toolbar

    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls)),
    ] + urlpatterns

services/web/backend/authentication/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import User


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm):
        model = User
        fields = ('username', 'password', 'email', 'first_name', 'last_name',
                  'name', 'region', 'picture', 'preferred_language',
                  'additional_data')


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'name', 'picture',
                  'preferred_language')

services/web/backend/authentication/views/authentication_and_callback.py
from django.shortcuts import redirect, render
from django.urls import reverse
from django.views.generic import View
from authentication.models import FederatedProvider
from django.conf import settings


class AuthenticationView(View):

    http_method_names = ["get"]

    def get(self, request):
        # if request.user.is_authenticated and (
        #     request.user.is_staff or request.user.is_superuser
        # ):
        #     next_url = request.session.get("next_authentication", reverse('admin:index'))
        #     return redirect(next_url)

        # Store the value of the next GET parameter
        if "next" in request.GET:
            request.session["next_authentication"] = request.GET.get("next")

        context = {
            "display_fastplatform_connector": True,
            "local_support_email_address": settings.LOCAL_SUPPORT_EMAIL_ADDRESS,
            "web_app_url": settings.WEB_APP_URL,
        }

        if "federated_provider_used" in request.session:
            context["federated_provider_used"] = request.session[
                "federated_provider_used"
            ]

        # if federated_provider parameter is present get only this federated_provider
        # else get all federated providers available
        if "federated_provider" in request.GET:
            federated_provider = FederatedProvider.objects.filter(
                id=request.GET.get("federated_provider"), is_active=True
            ).first()

            if federated_provider is not None:
                federated_providers = [federated_provider]
                context["display_fastplatform_connector"] = False
                if (
                    "force_authentication" in request.GET
                    and request.GET.get("force_authentication") == "true"
                ):
                    context["force_authentication"] = True
            else:
                federated_providers = FederatedProvider.objects.filter(is_active=True)
        else:
            federated_providers = FederatedProvider.objects.filter(is_active=True)

        context["federated_providers"] = federated_providers
        return render(request, "authentication/index.html", context)


class AuthenticationCallbackView(View):

    http_method_names = ["get"]

    def get(self, request):

        if request.user.is_authenticated:
            next_url = request.session.get("next_authentication", "/admin")

            return redirect(next_url)

        else:
            if "federated_provider" in request.GET:
                return redirect(
                    "/authentication?federated_provider="
                    + request.GET.get("federated_provider")
                )
            else:
                return redirect("/authentication")

services/web/backend/authentication/views/hasura.py
from django.http import JsonResponse
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import View

from authentication.views.utils import identify


class HasuraAuthWebhookView(View):
    """
    Hasura Webhook
    """

    http_method_names = ["get"]

    @method_decorator(csrf_exempt)
    def get(self, request):
        # Check if an authorization value is present
        # If not return a 401 Unauthorized

        identity = identify(request)

        if not identity:
            return JsonResponse({}, status=401)
        else:
            return JsonResponse(identity, status=200)

services/web/backend/authentication/views/logout.py
import json

from django.contrib.auth.views import LogoutView
from django.http import JsonResponse, HttpResponseRedirect
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import View

from oidc_provider.models import Token

from authentication.models import User


class OIDCLogoutView(View):

    http_method_names = ["post"]

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super(OIDCLogoutView, self).dispatch(request, *args, **kwargs)

    def post(self, request):
        body = json.loads(request.body)
        session_variables = body["session_variables"]

        authorization = request.META.get("HTTP_AUTHORIZATION", None)
        user_id = session_variables.get("x-hasura-user-id")

        if authorization and user_id:
            # The authentication webhook guarantees that the X-Hasura-User-Id
            # corresponds to the token in the Authorization header
            user = User.objects.get(id=user_id)

            access_token = authorization.split(" ")[1]
            oidc_token = Token.objects.get(access_token=Token.hash_token(access_token))
            oidc_token.delete()

            user.session_set.all().delete()

            return JsonResponse({"status": "ok", "username": user.username})
        else:
            return JsonResponse({"status": "error", "username": None})


class AuthenticationLogoutView(LogoutView):
    def dispatch(self, request, *args, **kwargs):

        if "federated_provider_logout_url" in request.session:
            federated_provider_logout_url = request.session[
                "federated_provider_logout_url"
            ]
            del request.session["federated_provider_logout_url"]
            return HttpResponseRedirect(federated_provider_logout_url)

        return super(AuthenticationLogoutView, self).dispatch(request, *args, **kwargs)

services/web/backend/authentication/views/terms_and_conditions.py
import json
import hashlib
import hmac
from datetime import datetime
from django.core.exceptions import ObjectDoesNotExist

from django.views.generic.base import TemplateView
from django.conf import settings
from django.contrib.auth.views import LogoutView
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse, HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect, render
from django.utils.decorators import method_decorator
from django.contrib.admin.views.decorators import staff_member_required

from authentication.models import (
    TermsAndConditionsConsentRequest,
    UserTermsAndConditionsConsent,
)


class TermsAndConditionsConsentRequestView(TemplateView):

    template_name = "authentication/terms_and_conditions.html"
    http_method_names = ["get", "post"]

    consent_request = None

    @method_decorator(login_required, staff_member_required)
    def dispatch(self, request, *args, **kwargs):
        consent_request_id = kwargs.pop("consent_request_id", None)
        try:
            self.consent_request = TermsAndConditionsConsentRequest.objects.get(
                pk=consent_request_id
            )
        except ObjectDoesNotExist:
            # This request does not exist, redirect
            return self._redirect_to_next(request, *args, **kwargs)

        # The user has already consented, redirect
        if UserTermsAndConditionsConsent.objects.filter(
            consent_request=self.consent_request, user=request.user
        ).exists():
            return self._redirect_to_next(request, *args, **kwargs)

        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):

        # Add the consent
        UserTermsAndConditionsConsent.objects.create(
            consent_request=self.consent_request, user=request.user
        )

        return self._redirect_to_next(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["consent_request"] = self.consent_request

        return context

    def _redirect_to_next(self, request, *args, **kwargs):
        if request.method == "post":
            next_url = request.POST.get("next", "/")
        else:
            next_url = request.GET.get("next", "/")

        if next_url == request.path:
            next_url = "/"

        return HttpResponseRedirect(next_url)

services/web/backend/authentication/templates/authentication/base.html
{% load i18n static %}

<!DOCTYPE html>
{% comment %} {% get_current_language as LANGUAGE_CODE %}{% get_current_language_bidi as LANGUAGE_BIDI %} {% endcomment %}
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}" {% if LANGUAGE_BIDI %}dir="rtl"{% endif %}>
<head>
<title>{% block title %}{% endblock %}</title>
<link rel="stylesheet" type="text/css" href="{% static "authentication/css/style.css" %}">
{% comment %} {% if LANGUAGE_BIDI %}<link rel="stylesheet" type="text/css" href="{% block stylesheet_rtl %}{% static "admin/css/rtl.css" %}{% endblock %}">{% endif %} {% endcomment %}
{% block extrahead %}{% endblock %}
{% block responsive %}
    <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static "admin/css/responsive.css" %}">
    {% comment %} {% if LANGUAGE_BIDI %}<link rel="stylesheet" type="text/css" href="{% static "admin/css/responsive_rtl.css" %}">{% endif %} {% endcomment %}
{% endblock %}
<!-- JavaScript -->
{% block extrascript %} {% endblock %}

</head>
{% load i18n %}

<body id="body" class="">

<!-- Container -->
<div id="container">

    <!-- Header -->
    <div class="position: fixed; top: 0; right: 0; left: 0; z-index: 1030;">
        {% include "authentication/header.html" %}
    </div>
    <!-- END Header -->

    <!-- Content -->
    <div id="content" style="background-color: rgb(23, 104, 145); height:100%; display:flex; padding-top:30px;">
        {% block content %}
        {% endblock %}
        <br class="clear">
    </div>
    <!-- END Content -->

    <div id="footer">{% include "authentication/footer.html" %}</div>
</div>
<!-- END Container -->

</body>
</html>

services/web/backend/authentication/templates/authentication/header.html
{% load static %}
<div class="d-flex justify-content-start" 
        style="position: relative; padding: 0 1rem 0 1rem; height: 60px;">
    <a href="https://ec.europa.eu/info/index_en" style="margin-top: 15px; margin-right: 1rem;">
        <img src="{% static "authentication/img/european_commission.svg" %}" style="height: 64px; display: block;">
    </a>
    <a href="/" id="header-title" 
        class="d-flex justify-content-start align-items-center text-decoration-none"
        style="height: 100%; color: black;">
        <img id="logo" src="{% static "authentication/img/logo.svg" %}" style="height: 60%; margin: 0 1rem 0 1rem;">
        <h1 class="font-family" style="margin: 0; margin-right: 16px;display: block; font-weight: 500 !important;">FaST</h1>
        <div class="font-family" style="padding-left: 16px; font-size: 1.5vw; font-weight: 100 !important; border-left: 1px solid silver;">{% trans 'EU Space Data for Sustainable Farming' %}</div>
    </a>
</div>

services/web/backend/authentication/templates/authentication/index.html
{% extends "admin/login.html" %}
{% load i18n static custom_tags %}

{% block extrastyle %}
  {{ block.super }}
  <link rel="stylesheet" type="text/css" href="{% static "admin/css/dashboard.css" %}">
{% endblock %}

{% block coltype %}colM{% endblock %}

{% block bodyclass %}{{ block.super }}{% endblock %}

{% block content %}

{% if messages %}
<ul class="errornote">
    {% for message in messages %}
    <li style="list-style: none;">{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

<div id="content-main">

{% if user.is_authenticated %}
  <div style="padding-bottom: 20px; border-bottom: 1px solid rgb(232, 232, 232);">
    <div style="line-height: 2em; margin-bottom: 4px;">
      {% trans 'You have been authenticated as'%}:
    </div>
    <div style="line-height: 2em; width: 100%; text-align: center;">
      <b>{% if user.name %}{{ user.name }} ({{ user.username }}){% else %}{{ user.username }}{% endif %}</b>
    </div>
  </div>
  
  <div style="margin: 20px 0;">
    {% trans 'Please choose where to go next:' %}
  </div>

  <div style="margin-top: 20px; ">
    <a href="{{ web_app_url }}" class="button" style="display: block; padding: 10px 15px; text-align: center; text-transform: uppercase; font-size: 13px;">{% trans 'Farmer mobile application' %}</a>
  </div>

  <div style="margin-top: 20px;">
    {% if user.is_staff %}
      <a href="{% url 'admin:index' %}" class="button" style="display: block; padding: 10px 15px; text-align: center; text-transform: uppercase; font-size: 13px;">{% trans 'Administration Portal' %}</a>
    {% else %}
      <span class="button" style="display: block; background-color: #CCC; width: auto; text-transform: uppercase; font-size: 13px; text-align: center;">{% trans 'Administration Portal' %}</span>
      <small style="display: block; color: #666; margin-top: 20px;">{% blocktrans %}You do not have the required status and permissions to access the Administration Portal. If you think you should be granted access, please contact your <a href="mailto:{{ local_support_email_address }}">local support</a>.{% endblocktrans %}</small>
    {% endif %}
  </div>

  <div style="line-height: 1.5em; width: 100%; margin-top: 20px; text-align: center;">
    {% trans 'Wrong user?' %} <a href="{% url 'authentication:logout' %}{% if request.GET.next %}?next={{ request.GET.next|as_absolute_url:request|urlencode }}{% endif %}">{% blocktrans %}Log out</a> and log in with a different user.{% endblocktrans %}
  </div>
  
{% else %}

  <div style="display: block; line-height: 2em; margin-bottom: 10px;">
    {% trans 'Choose your login method' %}:
  </div>

  {% for federated_provider in federated_providers %}
    <style>
      #{{ federated_provider.id }}-connector {
        display: block;
        border-radius: 4px;
        padding: 20px;
        margin-bottom: 20px;
        background-color: {{ federated_provider.background_color|default_if_none:"#DDDDDD" }} !important;
        color: {{ federated_provider.text_color|default_if_none:"#333333" }} !important;
        border: 1px solid #00000011;
        text-decoration: none;
      }
      #{{ federated_provider.id }}-connector:hover, #{{ federated_provider.id }}-connector:active {
        filter: opacity(0.8);
      }
    </style>
    <a href="{{ federated_provider.url }}{% if request.GET.next %}?next={{ request.GET.next|as_absolute_url:request|urlencode }}{% endif %}"
        id="{{ federated_provider.id }}-connector">
      {% if federated_provider.logo %}
        <img src="{{ federated_provider.logo.url }}" height="50" style="display: block; margin-bottom: 10px;"/>
      {% endif %}
      {% if federated_provider.name %}
      <h2>
          {{ federated_provider.name }}
      </h2>
      {% endif %}
      {% if federated_provider.description %}
        <h3 style="margin-top: 5px; font-weight: normal; opacity: 0.7; font-size: 12px; color: inherit;">
          {{ federated_provider.description }}
        </h3>
      {% endif %}
    </a>
  {% endfor %}
  {% if display_fastplatform_connector %}
    <style>
      #fastplatform-connector {
        display: block;
        border-radius: 4px;
        padding: 20px;
        background-color: var(--admin-interface-header-background-color) !important;
        color: #FFFFFF !important;
        border: 1px solid #00000011;
        text-decoration: none;
      }
      #fastplatform-connector:hover, #fastplatform-connector:active {
        filter: opacity(0.8);
      }
    </style>
    <a href="{% url 'authentication:login' %}{% if request.GET.next %}?next={{ request.GET.next|as_absolute_url:request|urlencode }}{% endif %}"
        id="fastplatform-connector">
      <img src="{% static "authentication/img/logo.svg" %}" height="50" style="display: block; margin-bottom: 10px;"/>
      <h2>FaST</h2>
      <h3 style="margin-top: 5px; font-weight: normal; opacity: 0.7; font-size: 12px; color: inherit;">
        {% trans 'For administrators and test users' %}
      </h3>
    </a>
  {% else %}
    {% if not force_authentication %}
      <div style="list-style: none !important; padding: 0; max-width: 250px; margin: auto; text-align: center; margin-top: 20px;">
        <a href="{% url 'authentication:index' %}" style="text-decoration: underline;">{% trans 'Display more login methods' %}</a>
      </div>
    {% endif %}
  {% endif %}

{% endif %}

</div>

{% if force_authentication %} 
  <script type="text/javascript">
    {% with federated_providers|first as federated_provider %}
      window.location.href = $( "#{{ federated_provider.id }}-connector").attr('href')
    {% endwith %}
  </script>
{% endif%}

{% endblock %}

services/web/backend/authentication/templates/authentication/lockout.html
{% extends "admin/login.html" %}
{% load i18n %}

{% block content %}

<div id="content-main">
  <p>
    {% blocktrans %}User <b>{{ username }}</b> has been locked out due to too many failed login attempts.{% endblocktrans %}
  </p>
  <p>
    Try again later.
  </p>
  <p>
    <a href="{% url 'admin:login' %}">{% trans "Go back" %}</a>
  </p>
</div>

{% endblock %}

services/web/backend/authentication/templates/authentication/login.html
{% extends "admin/login.html" %}
{% load i18n static %}

{% block content %}
{% if form.errors and not form.non_field_errors %}
<p class="errornote">
  {% if form.errors.items|length == 1 %}{% trans "Please correct the error below." %}{% else %}{% trans "Please correct
  the errors below." %}{% endif %}
</p>
{% endif %}

{% if form.non_field_errors %}
{% for error in form.non_field_errors %}
<p class="errornote">
  {{ error }}
</p>
{% endfor %}
{% endif %}

<div id="content-main">

  <form action="{{ app_path }}" method="post" id="login-form">{% csrf_token %}
    <div class="form-row">
      {{ form.username.errors }}
      {{ form.username.label_tag }} {{ form.username }}
    </div>
    <div class="form-row">
      {{ form.password.errors }}
      {{ form.password.label_tag }} {{ form.password }}
      <input type="hidden" name="next" value="{{ next }}">
    </div>
    <div class="password-reset-link">
      <a href="{% url 'authentication:password_reset' %}">{% trans 'Forgotten your password or username?' %}</a>
    </div>
    <div class="submit-row">
      <input type="submit" value="{% trans 'Log in' %}">
    </div>
  </form>


</div>
{% endblock %}

services/web/backend/authentication/templates/authentication/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}

{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'authentication:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% trans 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% trans "Thanks for using our site!" %}

{% blocktrans %}The {{ site_name }} team{% endblocktrans %}

{% endautoescape %}

services/web/backend/authentication/templates/authentication/terms_and_conditions.html
{% extends "admin/base_site.html" %}
{% load custom_tags static i18n %}
{% get_current_language as LANGUAGE_CODE %}

{% block title %}{{ consent_request.title }}{% endblock %}

{% block extrastyle %}
{{ block.super }}
<link rel="stylesheet" type="text/css" href="{% static "authentication/css/terms_and_conditions.css" %}">
<link rel="stylesheet" type="text/css" href="{% static "admin/css/forms.css" %}">
{% endblock %}

{% block coltype %}colMS{% endblock %}

{% block bodyclass %}{{ block.super }} terms-and-conditionqs{% endblock %}

{% block breadcrumbs %}
<div class="breadcrumbs">
{% trans "A new document or policy needs your attention" %}
</div>
{% endblock %}

{% block content %}
<h1>{% as_i18n consent_request "title" LANGUAGE_CODE %}</h1>
<div id="content-main">
    {% if consent_request.short_description %}
        <p>{% as_i18n consent_request "short_description" LANGUAGE_CODE %}</p>
    {% endif %}
    {% if consent_request.url %}
        <p>
            <a href="{% as_i18n consent_request "url" LANGUAGE_CODE %}" target="_blank">{% as_i18n consent_request "url" LANGUAGE_CODE %</a>
        </p>
    {% endif %}
    {% if consent_request.html_content %}
        <div class="terms-html-content">
            {% as_i18n consent_request "html_content" LANGUAGE_CODE %}
        </div>
    {% endif %}
    <form action="" method="post">
        {% csrf_token %}
        <div class="submit-row">
            <input type="submit" name="agree" class="default" value="{% trans "I agree" %}" />
        </div>
        <div style="width: 100%; margin-top: 40px; text-align: center;">
            {% trans 'Wrong user?' %} <a href="{% url 'authentication:logout' %}{% if request.GET.next %}?next={{ request.GET.next|as_absolute_url:request|urlencode }}{% endif %}">{% blocktrans %}Log out</a> and log in with a different user.{% endblocktrans %}
          </div>
    </form>
</div>
{% endblock %}

{% block sidebar %}
{% comment %} <div id="content-related">
    <div class="module toc">
        <h2>{% trans 'Table of contents' %}</h2>
        {{ markdown_toc }}
    </div>
</div> {% endcomment %}
{% endblock %}